[package]
name = "sinkmap"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0.22", features = ["derive"] }
anyhow = "1.0.66"
regex = "1"
